name: install_rust_by_version
  using: composite

  steps:
    - name: Install Rust (${{ matrix.version }})
      uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
      with:
          toolchain: ${{ matrix.version }}
