name: cache_cargo
description: caching .cargo directory
runs:
  using: composite

  steps:
    # Fix timestamps
    - name: restore timestamps
      uses: chetan/git-restore-mtime-action@v2
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ runner.version }}-${{ runner.release.name }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.version }}-${{ runner.release.name }}-cargo-

name: rm_cache_cargo
description: rm cache
runs:
  using: composite

  steps:
    - name: Clear the cargo caches
      run: |
        cargo install cargo-cache --no-default-features --features ci-autoclean
        cargo-cache

# https://zenn.dev/naokifujita/articles/c890954165c21f
# https://zenn.dev/kt3k/articles/d557cc874961ab
# https://github.com/marketplace/actions/git-restore-mtime
