name: cache_cargo
description: caching .cargo directory
runs:
  using: composite

  steps:
    # Fix timestamps
    - name: restore timestamps
      uses: chetan/git-restore-mtime-action@v2
    - name: Cache cargo registry pc-test
      if: runner.prefix == 'pc-test'
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ runner.version }}-${{ runner.prefix }}-${{ runner.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.version }}-${{ runner.prefix }}-${{ runner.target }}-cargo-
    - name: Cache cargo registry pc-run
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          examples/pc/target/
        key: ${{ runner.os }}-${{ runner.version }}-${{ runner.prefix }}-${{ runner.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-${{ runner.version }}-${{ runner.prefix }}-${{ runner.target }}-cargo-

# https://zenn.dev/naokifujita/articles/c890954165c21f
# https://zenn.dev/kt3k/articles/d557cc874961ab
# https://github.com/marketplace/actions/git-restore-mtime
