name: rm_cache_cargo
description: rm cache
runs:
  using: composite

  steps:
    - name: Clear the cargo caches powershell
      if: ${{ matrix.os == 'windows-latest' }}
      shell: powershell
      run: |
        cargo install cargo-cache --no-default-features --features ci-autoclean
        cargo-cache
    - name: Clear the cargo caches bash
      if: ${{ matrix.os != 'windows-latest' }}
      shell: bash
      run: |
        cargo install cargo-cache --no-default-features --features ci-autoclean --force
        cargo-cache
