name: rm_cache_cargo
description: rm cache
runs:
  using: composite

  steps:
    - name: Clear the cargo caches
      run: |
        cargo install cargo-cache --no-default-features --features ci-autoclean
        cargo-cache
