on: [push, pull_request]

jobs:
    build_cache:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: ./.github/actions/cache_cargo
            - name: build
              run: cargo build
              working-directory: .

    fmt:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        needs: build_cache
        steps:
            - uses: actions/checkout@v3
            - run: rustup component add rustfmt
            - uses: ./.github/actions/cache_cargo
            - name: fmt
              run: cargo fmt --all -- --check
              working-directory: .

    clippy:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        env:
            RUSTC_FORCE_INCREMENTAL: 1
        needs: build_cache
        steps:
            - uses: actions/checkout@v3
            - run: rustup component add clippy
            - uses: ./.github/actions/cache_cargo
            - name: clippy
              run: cargo clippy --all-targets --all-features -- -D warnings
              working-directory: .

    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        needs: build_cache
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/cache_cargo
            - name: test
              run: cargo test --all -- --nocapture
              working-directory: .
# https://zenn.dev/naokifujita/articles/c890954165c21f
