on: [push, pull_request]

jobs:
    test:
        name: test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: latest-stable
            # - name: install target
            #   run: rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
            - name: Install stable rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable
                  target: x86_64-apple-ios
            - name: Install LLVM and Clang
              uses: KyleMayes/install-llvm-action@v1.7.0
              with:
                  version: "13.0"
            - name: install rust iphone
              run: cargo install cargo-bundle --git https://github.com/burtonageo/cargo-bundle.git
            - name: pre build
              run: cargo build --target x86_64-apple-ios
              working-directory: ./examples/iphone/
            - name: build
              run: CARGO_BUNDLE_SKIP_BUILD=1 cargo bundle --format ios --target x86_64-apple-ios
              working-directory: ./examples/iphone/
              continue-on-error: true
            - name: install tree
              run: brew install tree
            - name: tree
              run: tree target
              working-directory: ./examples/iphone/
            - name: start simulator
              uses: futureware-tech/simulator-action@v3
              with:
                  model: "iPhone 8"
            - name: drive
              run: |
                  xcrun simctl install booted target/x86_64-apple-ios/debug/bundle/ios/nickname-ios-test-app.app
                  xcrun simctl launch --console booted com.oligami.nickname-ios-test
              working-directory: ./examples/iphone/
# https://github.com/simlay/uikit-sys/blob/master/.github/workflows/rust.yml
