on: [push, pull_request]

jobs:
    test:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 8
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: current
            - name: Run Android Emulator
              run: |
                  echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-32;google_apis;x86_64'
                  echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n xamarin_android_emulator -k 'system-images;android-32;google_apis;x86_64' --force
                  echo $ANDROID_HOME/emulator/emulator -list-avds
                  echo "Starting emulator"
                  nohup $ANDROID_HOME/emulator/emulator -avd xamarin_android_emulator -debug-init -no-snapshot > /dev/null 2>&1 &
                  $ANDROID_HOME/platform-tools/adb devices
                  echo "Emulator started"
            - name: install target
              run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android
            - name: install rust android
              run: cargo install cargo-apk
            - name: catch log
              run: adb logcat RustStdoutStderr:D '*:S' > cargo-apk.log &
            - name: Run tests
              run: cargo apk run
              working-directory: ./examples/android/
              continue-on-error: true
            - name: Upload log on cargo-apk
              uses: actions/upload-artifact@v1
              with:
                  name: cargo-apk.log
                  path: cargo-apk.log
            - name: Upload screenshots
              uses: actions/upload-artifact@v1
              with:
                  name: screenshots
                  path: screenshots
# https://zenn.dev/takeyaqa/articles/github-actions-appium-android-emulator
# https://stackoverflow.com/questions/3152681/android-emulator-5554-offline

