on: [push, pull_request]

jobs:
    test:
        name: test
        strategy:
            matrix:
                api-level: [24, 30, 33]
            fail-fast: false
        runs-on: macOS-11
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 11
            - name: install target
              run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
            - name: install rust android
              run: cargo install cargo-apk
            - name: catch log
              run: adb logcat RustStdoutStderr:D '*:S' > cargo-apk.log &
            - name: create instrumentation coverage
              uses: ReactiveCircus/android-emulator-runner@v2
              env:
                  GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.network.retry.max.attempts=6 -Dorg.gradle.internal.network.retry.initial.backOff=2000"
              if: ${{ matrix.api-level != 33 }}
              with:
                  api-level: ${{ matrix.api-level }}
                  target: default
                  arch: x86_64
                  profile: pixel_2
                  ram-size: "4096M"
                  disk-size: "14G"
                  sdcard-path-or-size: "1000M"
                  disable-animations: false
                  script: |
                      adb root
                      cargo apk run
                  working-directory: ./examples/android/
                  continue-on-error: true
            - name: create instrumentation coverage on google_apis for android 33
              uses: ReactiveCircus/android-emulator-runner@v2
              env:
                  GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.network.retry.max.attempts=6 -Dorg.gradle.internal.network.retry.initial.backOff=2000"
              if: ${{ matrix.api-level == 33 }}
              with:
                  api-level: ${{ matrix.api-level }}
                  target: google_apis
                  arch: x86_64
                  profile: pixel_2
                  heap-size: "512M"
                  ram-size: "4096M"
                  disk-size: "14G"
                  sdcard-path-or-size: "4096M"
                  disable-animations: false
                  script: |
                      adb root
                      cargo apk run
                  working-directory: ./examples/android/
                  continue-on-error: true
            - name: Upload log on cargo-apk
              uses: actions/upload-artifact@v1
              with:
                  name: cargo-apk.log
                  path: cargo-apk.log
# https://zenn.dev/takeyaqa/articles/github-actions-appium-android-emulator
# https://stackoverflow.com/questions/3152681/android-emulator-5554-offline

# nohup $ANDROID_HOME/emulator/emulator -avd xamarin_android_emulator -debug-init -no-snapshot > /dev/null 2>&1 &
# https://github.com/kiwix/kiwix-android/blob/develop/.github/workflows/ci.yml
