on: [push, pull_request]

jobs:
    test:
        name: test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: latest-stable
            # - name: install target
            #   run: rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
            - name: Install stable rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable
                  target: x86_64-apple-ios
                  override: true
            # - name: install rust iphone
            #   run: cargo install cargo-bundle --git https://github.com/burtonageo/cargo-bundle.git
            - name: Install cargo-dinghy
              uses: baptiste0928/cargo-install@v2
              with:
                  crate: cargo-dinghy
            - name: pre build
              run: cargo build --target x86_64-apple-ios
              working-directory: ./examples/iphone/
            - name: build
              run: CARGO_BUNDLE_SKIP_BUILD=1 cargo bundle --format ios --target x86_64-apple-ios
              working-directory: ./examples/iphone/
              continue-on-error: true
            - name: install tree
              run: brew install tree
            - name: tree
              run: tree target
              working-directory: ./examples/iphone/
            - name: start simulator
              uses: futureware-tech/simulator-action@v3
              with:
                  model: "iPhone 8"
            # - name: drive
            #   run: |
            #       xcrun simctl install booted target/x86_64-apple-ios/debug/bundle/ios/nickname-ios-test-app.app
            #       xcrun simctl launch --console booted com.oligami.nickname-ios-test
            #   working-directory: ./examples/iphone/

            - name: Dinghy test
              run: |
                  cargo dinghy --platform auto-ios-x86_64 test

# https://github.com/simlay/uikit-sys/blob/master/.github/workflows/rust.yml
