on: [push, pull_request]

jobs:
    test:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v3
            - name: install target
              run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android
            - name: install rust android
              run: cargo install cargo-apk
            - name: catch log
              run: adb logcat RustStdoutStderr:D '*:S' > cargo-apk.log &
            - name: AVD cache
              uses: actions/cache@v3
              id: avd-cache
              with:
                  path: |
                      ~/.android/avd/*
                      ~/.android/adb*
                  key: avd-32
            - name: create AVD and generate snapshot for caching
              if: steps.avd-cache.outputs.cache-hit != 'true'
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 32
                  arch: "x86_64"
                  target: google_apis
                  force-avd-creation: false
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: false
                  script: echo "Generated AVD snapshot for caching."
            - name: run tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 32
                  arch: "x86_64"
                  target: google_apis
                  force-avd-creation: false
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  script: cargo apk run
                  working-directory: ./examples/android/
            - name: Upload log on cargo-apk
              uses: actions/upload-artifact@v1
              with:
                  name: cargo-apk.log
                  path: cargo-apk.log
# https://zenn.dev/takeyaqa/articles/github-actions-appium-android-emulator
# https://stackoverflow.com/questions/3152681/android-emulator-5554-offline

# nohup $ANDROID_HOME/emulator/emulator -avd xamarin_android_emulator -debug-init -no-snapshot > /dev/null 2>&1 &
